[phases.setup]
nixPkgs = [
  "cmake",
  "boost",
  "gcc",
  "pkg-config",
  "python3",
  "python3Full",
  "python3-dev",
  "libffi",
  "zlib",
  "libjpeg",
  "libpng"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install wheel",
  "pip install -r requirements.txt"
]

[variables]
PYTHON_VERSION = "3.9"
