[phases.setup]
nixPkgs = [
  "python310Full",   # Includes python3 and pip
  "cmake",
  "gcc",
  "boost",
  "pkg-config",
  "libffi",
  "zlib",
  "libjpeg",
  "libpng"
]

[phases.install]
cmds = [
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/nixpkgs-23.11-darwin.tar.gz"
cmds = []
