[phases.setup]
nixPkgs = ["cmake", "gcc", "boost", "pkg-config", "libffi", "zlib", "libjpeg", "libpng"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install wheel",
  "python3 -m pip install -r requirements.txt"
]

[variables]
PYTHON_VERSION = "3.10"
