[phases.setup]
nixPkgs = [
  "python310",
  "cmake",
  "gcc",
  "boost",
  "pkg-config",
  "libffi",
  "zlib",
  "libjpeg",
  "libpng"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install wheel",
  "pip install -r requirements.txt"
]
